### ISSUE TITLE
Started Porting of expose.xmlrpc

### ISSUE THREAD

**Issue by merlink01** [althonos/fs.expose#1]
@althonos, could you please have a look at this.

https://github.com/merlink01/fs.expose

Would be nice to know if the structure is correct for you plans.

**Comment by althonos** [comment]
Don't worry about the structure, I can refactor if needed. Juste make sure the code is tested with full coverage, and I'll make sure it integrates well.

**Comment by merlink01** [comment]
Fine, thank you.
